export const upgradeCards = [
  {id: 61, type: 'special', rune: 'Y', attribute: 'fury', value: 2, flavorText: 'Avance 2 de fúria', player: true},
  {id: 62, type: 'special', rune: 'X', attribute: 'life', value: 4, flavorText: 'Cure 4 pontos de vida', player: true},
  {id: 63, type: 'special', rune: 'F', attribute: 'life', value: 2, flavorText: 'Cada herói cura 2', team: true},
  {id: 64, type: 'special', rune: 'Y', attribute: 'card', value: 1, flavorText: 'Cada herói compra 1', team: true},
  {id: 65, type: 'special', rune: 'F', attribute: 'card', value: 2, flavorText: 'Compra 2', player: true},
  {id: 66, type: 'special', rune: 'R', attribute: 'life', value: undefined, flavorText: 'Descarte um (+) para curar a mesma quantidade em algum heroi', player: true, team: true},
  {id: 67, type: 'defense', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 68, type: 'defense', rune: 'R', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 69, type: 'defense', rune: 'F', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 610, type: 'defense', rune: 'F', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 611, type: 'defense', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 612, type: 'defense', rune: 'X', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 671, type: 'attack_melee', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 682, type: 'attack_melee', rune: 'R', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 693, type: 'attack_melee', rune: 'F', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 6104, type: 'attack_melee', rune: 'F', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 6115, type: 'attack_melee', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 6126, type: 'attack_melee', rune: 'X', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 6711, type: 'attack_reach', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 6822, type: 'attack_reach', rune: 'R', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 6933, type: 'attack_reach', rune: 'F', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 61044, type: 'attack_reach', rune: 'F', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 61155, type: 'attack_reach', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 61266, type: 'attack_reach', rune: 'X', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 67111, type: 'power', rune: 'Y', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 68222, type: 'power', rune: 'R', attribute: 'power', value: 2, flavorText: '+2', player: true},
  {id: 69333, type: 'power', rune: 'F', attribute: 'power', value: 3, flavorText: '+3', player: true},
  {id: 610444, type: 'power', rune: 'F', attribute: 'power', value: 4, flavorText: '+4', player: true},
  {id: 611555, type: 'power', rune: 'Y', attribute: 'power', value: 4, flavorText: '+4', player: true},
  {id: 612666, type: 'power', rune: 'X', attribute: 'power', value: 3, flavorText: '+3', player: true}
]